Use ReTest
BioJulia/FASTX.jl pull request #84
Opened 2022-08-14 15:23 UTC by kescobo

Branched off of #68 . Closes #83

2022-08-14 16:00 UTC, kescobo commented
@jakobnissen [So this is a bummer](https://juliatesting.github.io/ReTest.jl/stable/#Including-files-from-within-testsets)

How married to the nesting testsets are you? I could preserve it by making each of the sub-files a new module (eg TestFASTA.IO - it would be a bit of a hassle since each thing would need to re-do imports etc. Another option is to just include the name in all of the testsets (eg `@testset "IO - Reader Basics" begin`. Then one can do `retest(TestFASTA, "IO") to run them in isolation.

I'm partial to the last one. You can pass multiple filters, so eg if you want the "basic" tests, but only the ones from "IO", you can do `retest(TestFASTA, "IO", "basic")`.

2022-08-14 16:20 UTC, kescobo commented
Argh, actually, that doesn't work as well because it doesn't pick up on changes to the `include`d files with Revise. I'll just make submodules.

2022-08-14 17:52 UTC, jakobnissen commented
I don't really have any opinions, since I haven't used ReTest for any real project yet.

2022-08-15 16:54 UTC, kescobo commented
Alright, I think this should work. I've added a `test/README.md` to describe what to do, please take a look and let me know if it makes sense.

2022-08-15 17:12 UTC, kescobo commented
Hm... don't see why julia 1.6 would be different here.

2022-08-15 19:03 UTC, kescobo commented
Oh, the problem is windows/mac, not the julia version :thinking: 

I only have linux box, anyone with mac/windows have a thought

2022-08-15 19:47 UTC, kescobo commented
@jakobnissen OK, I think this is good to go

2022-08-16 08:05 UTC, jakobnissen requested changes
Real nice.

2022-08-16 08:07 UTC, jakobnissen approved these changes
Real nice.

2022-08-16 08:07 UTC, jakobnissen commented on src/FASTX.jl
> +
```suggestion
```

2022-08-16 08:07 UTC, jakobnissen commented on test/README.md
> +
```suggestion
❯ julia --project -q
```

2022-08-16 08:08 UTC, merged